StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{610CC601305EA2CA}" {
   Id "PS-Callsign_PS_Civilians_Company_0"
   Target_en_us "Завод"
   Modified 1628229998
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610CC6001A57DEA7}" {
   Id "PS-Callsign_PS_Civilians_Platoon_0"
   Target_en_us "Сыров"
   Modified 1628230029
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610CC600284860B2}" {
   Id "PS-Callsign_PS_Civilians_Squad_0"
   Target_en_us "№ 1"
   Modified 1628230051
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61056091B61469A1}" {
   Id "PS-Callsign_PS_Criminals_Company_0"
   Target_en_us "Артель"
   Target_ru_ru "Артель"
   Modified 1627813221
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61056091B8FDEC6A}" {
   Id "PS-Callsign_PS_Criminals_Company_1"
   Target_en_us "Банда"
   Target_ru_ru "Банда"
   Modified 1627813218
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61056091B9476FE4}" {
   Id "PS-Callsign_PS_Criminals_Company_2"
   Target_en_us "Ватага"
   Target_ru_ru "Ватага"
   Modified 1627813224
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61056091BB1B815D}" {
   Id "PS-Callsign_PS_Criminals_Company_3"
   Target_en_us "Группа"
   Target_ru_ru "Группа"
   Modified 1627813227
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61056091285F3F01}" {
   Id "PS-Callsign_PS_Criminals_Platoon_0"
   Target_en_us "Афериста"
   Target_ru_ru "Афериста"
   Modified 1627813230
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609E8B4517F0}" {
   Id "PS-Callsign_PS_Criminals_Platoon_1"
   Target_en_us "Буйного"
   Target_ru_ru "Буйного"
   Modified 1627828706
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609FB442003E}" {
   Id "PS-Callsign_PS_Criminals_Platoon_2"
   Target_en_us "Весельчака"
   Target_ru_ru "Весельчака"
   Modified 1627853952
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609F49FD613F}" {
   Id "PS-Callsign_PS_Criminals_Platoon_3"
   Target_en_us "Гангстера"
   Target_ru_ru "Гангстера"
   Modified 1627813238
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609DB81F6861}" {
   Id "PS-Callsign_PS_Criminals_Squad_0"
   Target_en_us "Агриппы"
   Target_ru_ru "Агриппы"
   Modified 1627813241
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609D44115D34}" {
   Id "PS-Callsign_PS_Criminals_Squad_1"
   Target_en_us "Бадюка"
   Target_ru_ru "Бадюка"
   Modified 1627813248
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609D6D6343ED}" {
   Id "PS-Callsign_PS_Criminals_Squad_2"
   Target_en_us "Вартаняна"
   Target_ru_ru "Вартаняна"
   Modified 1627813251
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6105609D356568FB}" {
   Id "PS-Callsign_PS_Criminals_Squad_3"
   Target_en_us "Гоги"
   Target_ru_ru "Гоги"
   Modified 1627813253
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610CC6046E53CF5A}" {
   Id "PS-Faction_Civilians"
   Target_en_us "Civilians"
   Target_ru_ru "Гражданские"
   Modified 1628230944
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610CC60476D64346}" {
   Id "PS-Faction_Civilians-UC"
   Target_en_us "CIVILIANS"
   Target_ru_ru "ГРАЖДАНСКИЕ"
   Modified 1628230938
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6106934317DA497B}" {
   Id "PS-Faction_Criminals"
   Target_en_us "Criminals"
   Target_ru_ru "ОПГ"
   Modified 1627853967
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610693432358DE21}" {
   Id "PS-Faction_Criminals_UC"
   Target_en_us "CRIMINALS"
   Target_ru_ru "ОПГ"
   Modified 1628235628
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6106F6D14F996178}" {
   Id "PS-Item_Noquia2028_Description"
   Target_en_us "Unlike the first version of Noqia 2018, the next generation device is larger in size, equipped with a 2.4-inch display with a resolution of 320x240 pixels, a two-megapixel camera and supports microSD memory cards."
   Target_ru_ru "В отличие от первой версии Noqia 2018, устройство следующего поколения больше по размеру, снабжено 2,4-дюймовым дисплеем с разрешением 320х240 пикселей, двухмегапиксельной камерой и поддерживает карты памяти microSD."
   Modified 1627847351
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{6106F6D1479B4D87}" {
   Id "PS-Item_Noquia2028_Name"
   Target_en_us "Noquia 2028"
   Target_ru_ru "Noquia 2028"
   Modified 1627847133
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7964FEBBB}" {
   Id "PS-Role_CR_Boss"
   Target_en_us "Босс"
   Modified 1627813646
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7421EEDE6}" {
   Id "PS-Role_CR_Brigadier"
   Target_en_us "Бригадир"
   Modified 1627813928
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7980E951B}" {
   Id "PS-Role_CR_Capo"
   Target_en_us "Капо"
   Modified 1627813649
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D79DEC30AF}" {
   Id "PS-Role_CR_Gangster"
   Target_en_us "Гангстер"
   Modified 1627813653
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7A3465820}" {
   Id "PS-Role_CR_Gorilla"
   Target_en_us "Горила"
   Modified 1627813813
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7AE42D2BB}" {
   Id "PS-Role_CR_Gunman"
   Target_en_us "Стрелок"
   Modified 1627813849
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D747A0250C}" {
   Id "PS-Role_CR_Hijacker"
   Target_en_us "Угонщик"
   Modified 1627813874
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7A08A4C51}" {
   Id "PS-Role_CR_Killer"
   Target_en_us "Киллер"
   Modified 1627813867
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{61069374DFDAF657}" {
   Id "PS-Role_CR_Mercenary"
   Target_en_us "Наемник"
   Target_ru_ru "Наемник"
   Modified 1627838458
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7ABA36D06}" {
   Id "PS-Role_CR_Outlaw"
   Target_en_us "Преступник"
   Modified 1627813882
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7B7ACD263}" {
   Id "PS-Role_CR_Racketeer"
   Target_en_us "Рэкетир"
   Modified 1627813891
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7BDF302F4}" {
   Id "PS-Role_CR_Ruffian"
   Target_en_us "Хулиган"
   Modified 1627813938
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D74B5730ED}" {
   Id "PS-Role_CR_Taskmaster"
   Target_en_us "Воротила"
   Modified 1627813986
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D75048E07E}" {
   Id "PS-Role_CR_Thug"
   Target_en_us "Бандит"
   Modified 1627813922
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D7B2DBD19A}" {
   Id "PS-Role_CR_Tough"
   Target_en_us "Головорез"
   Modified 1627813946
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610560D74E0A136E}" {
   Id "PS-Role_CR_Yegg"
   Target_en_us "Взломщик"
   Modified 1627813964
   Author "zazul"
   LastChanged "zazul"
  }
  CustomStringTableItem "{610CC602AA0B7193}" {
   Id "PS-Role_VeganSiroed"
   Target_en_us "Веган сыроед"
   Modified 1628230743
   Author "zazul"
   LastChanged "zazul"
  }
 }
}